### ISSUE TITLE
Admin: CSV does not download correct member set

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#103]
Tried to do a CSV download and got random group of people. Only 70 entries rather than 228 total members.

**Comment by seekingsnowflakes** [comment]
Confirmed that this is still an issue.

**Comment by bradnoble** [comment]
I started looking at this. I appears to be a bug that rears its head when we have people who are not associated to households. (ie, it's not a random group of people, it's just an incomplete dump of 'all'.)

**Comment by bradnoble** [comment]
This has turned out to be more complicated than originally assumed. Turns out the issue is a sneaky one -- the database will only return a max of 200 results per request. In order to get all of the records, I need to page through results and compile them until I reach the end. Will require more experimentation. I'm not the first one to bump into this, so it shouldn't be too bad. No estimate yet.

**Comment by bradnoble** [comment]
Now you can build a report to download, select the statuses you want included, preview it, and see the statuses you selected in a simpler filename.

**Comment by seekingsnowflakes** [comment]
@bradnoble should I try actually deleting one of them to verify? Snazzy though.

**Comment by bradnoble** [comment]
That is correct, once we purge the dead heads, we can close this.

**Comment by bradnoble** [comment]
@seekingsnowflakes this can be closed, once the incompletes are blown away.

**Comment by seekingsnowflakes** [comment]
Looks good.
