### ISSUE TITLE
Admin: Summary data panel has Submit button but no editable fields

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#38]
To reproduce:

1. Select Admin in topbar menu
2. Select edit icon for household
3. After household edit page is displayed select Summary tab
4. Summary data is displayed w/ Submit button but there do not appear to be any editable fields

**Comment by seekingsnowflakes** [comment]
Believe this has been reworked so that the summary tabs described are no longer applicable. Current view:

![image](https://user-images.githubusercontent.com/34328388/40695607-e67f9e28-638f-11e8-829a-155f6611843c.png)

Will note that the edit pane here seems really large - it doesn't fit on a single screen, even though the fonts are pretty small.
