### ISSUE TITLE
Double click on folder name in resources list results in duplicate breadcrumbs

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#43]
Lodge public folder has two "Lodge"s in the traceback

**Comment by idevtech** [comment]
What do you mean by "traceback"?

**Comment by seekingsnowflakes** [comment]
The breadcrumbs path seems to repeat the first level folder if going deeper.

**Comment by idevtech** [comment]
Hmmm... This is what a multi-level breadcrumb path looks like here which is the expected behavior. If your display is different for the same path please post a screen capture and what browser you're using.

![screen shot 2018-05-18 at 7 12 47 am](https://user-images.githubusercontent.com/486002/40232066-59d99bb8-5a6b-11e8-8a75-cca616064251.png)

**Comment by seekingsnowflakes** [comment]
Jim has noted in spreadsheet issue row 7 that this occurs when double-clicking on a folder name.
![double_foldername](https://user-images.githubusercontent.com/34328388/40692851-13363d68-6382-11e8-9493-b05e18022389.JPG)

**Comment by idevtech** [comment]
Added logic to test whether loading of a folder is in progress and whether the requested folder is the same as the folder currently displayed.

**Comment by seekingsnowflakes** [comment]
Appears fixed.
